export interface Currency {
  code: string;
  name: string;
  flag: string;
  region: 'americas' | 'europa' | 'asia' | 'africa' | 'outros';
  isPrincipal: boolean;
  color: string;
}

export const CURRENCIES: Record<string, Currency> = {
  USD: {
    code: 'USD',
    name: 'Dólar Americano',
    flag: '🇺🇸',
    region: 'americas',
    isPrincipal: true,
    color: 'bg-emerald-600',
  },
  EUR: {
    code: 'EUR',
    name: 'Euro',
    flag: '🇪🇺',
    region: 'europa',
    isPrincipal: true,
    color: 'bg-blue-700',
  },
  GBP: {
    code: 'GBP',
    name: 'Libra Esterlina',
    flag: '🇬🇧',
    region: 'europa',
    isPrincipal: true,
    color: 'bg-indigo-800',
  },
  JPY: {
    code: 'JPY',
    name: 'Iene Japonês',
    flag: '🇯🇵',
    region: 'asia',
    isPrincipal: true,
    color: 'bg-rose-600',
  },
  CHF: {
    code: 'CHF',
    name: 'Franco Suíço',
    flag: '🇨🇭',
    region: 'europa',
    isPrincipal: true,
    color: 'bg-red-500',
  },
  AUD: {
    code: 'AUD',
    name: 'Dólar Australiano',
    flag: '🇦🇺',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-800',
  },
  CAD: {
    code: 'CAD',
    name: 'Dólar Canadense',
    flag: '🇨🇦',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  CNY: {
    code: 'CNY',
    name: 'Yuan Chinês',
    flag: '🇨🇳',
    region: 'asia',
    isPrincipal: true,
    color: 'bg-red-600',
  },
  ARS: {
    code: 'ARS',
    name: 'Peso Argentino',
    flag: '🇦🇷',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-sky-400',
  },
  DKK: {
    code: 'DKK',
    name: 'Coroa Dinamarquesa',
    flag: '🇩🇰',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-red-700',
  },
  NOK: {
    code: 'NOK',
    name: 'Coroa Norueguesa',
    flag: '🇳🇴',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-blue-900',
  },
  SEK: {
    code: 'SEK',
    name: 'Coroa Sueca',
    flag: '🇸🇪',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  RUB: {
    code: 'RUB',
    name: 'Rublo Russo',
    flag: '🇷🇺',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-slate-500',
  },
  MXN: {
    code: 'MXN',
    name: 'Peso Mexicano',
    flag: '🇲🇽',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-green-800',
  },
  SGD: {
    code: 'SGD',
    name: 'Dólar de Singapura',
    flag: '🇸🇬',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  HKD: {
    code: 'HKD',
    name: 'Dólar de Hong Kong',
    flag: '🇭🇰',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  KRW: {
    code: 'KRW',
    name: 'Won Sul-Coreano',
    flag: '🇰🇷',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-slate-700',
  },
  INR: {
    code: 'INR',
    name: 'Rúpia Indiana',
    flag: '🇮🇳',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-orange-500',
  },
  NZD: {
    code: 'NZD',
    name: 'Dólar Neozelandês',
    flag: '🇳🇿',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-900',
  },
  ZAR: {
    code: 'ZAR',
    name: 'Rand Sul-Africano',
    flag: '🇿🇦',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-green-700',
  },
  CLP: {
    code: 'CLP',
    name: 'Peso Chileno',
    flag: '🇨🇱',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-red-800',
  },
  COP: {
    code: 'COP',
    name: 'Peso Colombiano',
    flag: '🇨🇴',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-yellow-500',
  },
  PEN: {
    code: 'PEN',
    name: 'Sol Peruano',
    flag: '🇵🇪',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-red-700',
  },
  UYU: {
    code: 'UYU',
    name: 'Peso Uruguaio',
    flag: '🇺🇾',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-sky-600',
  },
  PYG: {
    code: 'PYG',
    name: 'Guarani Paraguaio',
    flag: '🇵🇾',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  BOB: {
    code: 'BOB',
    name: 'Boliviano',
    flag: '🇧🇴',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-green-600',
  },
  ILS: {
    code: 'ILS',
    name: 'Novo Shekel Israelense',
    flag: '🇮🇱',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-600',
  },
  SAR: {
    code: 'SAR',
    name: 'Riyal Saudita',
    flag: '🇸🇦',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-green-700',
  },
  AED: {
    code: 'AED',
    name: 'Dirham dos EAU',
    flag: '🇦🇪',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-slate-600',
  },
  TRY: {
    code: 'TRY',
    name: 'Lira Turca',
    flag: '🇹🇷',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-red-700',
  },
  PLN: {
    code: 'PLN',
    name: 'Zloty Polonês',
    flag: '🇵🇱',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  HUF: {
    code: 'HUF',
    name: 'Florim Húngaro',
    flag: '🇭🇺',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-green-600',
  },
  CZK: {
    code: 'CZK',
    name: 'Coroa Checa',
    flag: '🇨🇿',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-blue-700',
  },
  THB: {
    code: 'THB',
    name: 'Baht Tailandês',
    flag: '🇹🇭',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-indigo-500',
  },
  IDR: {
    code: 'IDR',
    name: 'Rupia Indonésia',
    flag: '🇮🇩',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  MYR: {
    code: 'MYR',
    name: 'Ringgit Malaio',
    flag: '🇲🇾',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-yellow-600',
  },
  PHP: {
    code: 'PHP',
    name: 'Peso Filipino',
    flag: '🇵🇭',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  BHD: {
    code: 'BHD',
    name: 'Dinar Bareinita',
    flag: '🇧🇭',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  KWD: {
    code: 'KWD',
    name: 'Dinar Kuwaitiano',
    flag: '🇰🇼',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-400',
  },
  QAR: {
    code: 'QAR',
    name: 'Riyal Catariano',
    flag: '🇶🇦',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-purple-800',
  },
  OMR: {
    code: 'OMR',
    name: 'Riyal Omanense',
    flag: '🇴🇲',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-700',
  },
  JOD: {
    code: 'JOD',
    name: 'Dinar Jordaniano',
    flag: '🇯🇴',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-slate-500',
  },
  EGP: {
    code: 'EGP',
    name: 'Libra Egípcia',
    flag: '🇪🇬',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-slate-800',
  },
  DZD: {
    code: 'DZD',
    name: 'Dinar Argelino',
    flag: '🇩🇿',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-green-800',
  },
  MAD: {
    code: 'MAD',
    name: 'Dirham Marroquino',
    flag: '🇲🇦',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  CRC: {
    code: 'CRC',
    name: 'Colón Costarriquenho',
    flag: '🇨🇷',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-blue-600',
  },
  TWD: {
    code: 'TWD',
    name: 'Novo Dólar Taiwanês',
    flag: '🇹🇼',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  RON: {
    code: 'RON',
    name: 'Leu Romeno',
    flag: '🇷🇴',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-yellow-500',
  },
  BGN: {
    code: 'BGN',
    name: 'Lev Búlgaro',
    flag: '🇧🇬',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-green-600',
  },
  ISK: {
    code: 'ISK',
    name: 'Coroa Islandesa',
    flag: '🇮🇸',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-blue-800',
  },
  VES: {
    code: 'VES',
    name: 'Bolívar Soberano',
    flag: '🇻🇪',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-yellow-700',
  },
  VND: {
    code: 'VND',
    name: 'Dong Vietnamita',
    flag: '🇻🇳',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-rose-700',
  },
  TJS: {
    code: 'TJS',
    name: 'Somoni do Tajiquistão',
    flag: '🇹🇯',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-green-500',
  },
  TMT: {
    code: 'TMT',
    name: 'Manat Turcomeno',
    flag: '🇹🇲',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-green-900',
  },
  UZS: {
    code: 'UZS',
    name: 'Som Uzbeque',
    flag: '🇺🇿',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-400',
  },
  PKR: {
    code: 'PKR',
    name: 'Rúpia Paquistanesa',
    flag: '🇵🇰',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-green-600',
  },
  LKR: {
    code: 'LKR',
    name: 'Rúpia do Sri Lanka',
    flag: '🇱🇰',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-800',
  },
  KES: {
    code: 'KES',
    name: 'Xelim Queniano',
    flag: '🇰🇪',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-red-700',
  },
  NGN: {
    code: 'NGN',
    name: 'Naira Nigeriana',
    flag: '🇳🇬',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-green-500',
  },
  TND: {
    code: 'TND',
    name: 'Dinar Tunisiano',
    flag: '🇹🇳',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  GEL: {
    code: 'GEL',
    name: 'Lari Georgiano',
    flag: '🇬🇪',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  AZN: {
    code: 'AZN',
    name: 'Manat Azerbaijano',
    flag: '🇦🇿',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  BYN: {
    code: 'BYN',
    name: 'Rublo Bielorrusso',
    flag: '🇧🇾',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  KZT: {
    code: 'KZT',
    name: 'Tenge Cazaque',
    flag: '🇰🇿',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-blue-600',
  },
  MDL: {
    code: 'MDL',
    name: 'Leu Moldavo',
    flag: '🇲🇩',
    region: 'europa',
    isPrincipal: false,
    color: 'bg-blue-700',
  },
  KGS: {
    code: 'KGS',
    name: 'Som Quirguiz',
    flag: '🇰🇬',
    region: 'asia',
    isPrincipal: false,
    color: 'bg-red-500',
  },
  DOP: {
    code: 'DOP',
    name: 'Peso Dominicano',
    flag: '🇩🇴',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  GTQ: {
    code: 'GTQ',
    name: 'Quetzal de Guatemala',
    flag: '🇬🇹',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-green-600',
  },
  HNL: {
    code: 'HNL',
    name: 'Lempira de Honduras',
    flag: '🇭🇳',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-blue-800',
  },
  NIO: {
    code: 'NIO',
    name: 'Córdoba de Nicarágua',
    flag: '🇳🇮',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-blue-500',
  },
  PAB: {
    code: 'PAB',
    name: 'Balboa de Panamá',
    flag: '🇵🇦',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-blue-600',
  },
  BZD: {
    code: 'BZD',
    name: 'Dólar de Belize',
    flag: '🇧🇿',
    region: 'americas',
    isPrincipal: false,
    color: 'bg-green-700',
  },
  GHS: {
    code: 'GHS',
    name: 'Cedi de Gana',
    flag: '🇬🇭',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-yellow-500',
  },
  MUR: {
    code: 'MUR',
    name: 'Rúpia Mauriciana',
    flag: '🇲🇺',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-red-600',
  },
  ETB: {
    code: 'ETB',
    name: 'Birr Etíope',
    flag: '🇪🇹',
    region: 'africa',
    isPrincipal: false,
    color: 'bg-green-700',
  },
};

export const REGION_LABELS: Record<string, string> = {
  americas: 'Américas',
  europa: 'Europa',
  asia: 'Ásia/Oceania',
  africa: 'África',
  outros: 'Outras Regiões',
};

export const REGION_COLORS: Record<string, string> = {
  americas: 'text-blue-600',
  europa: 'text-purple-600',
  asia: 'text-orange-600',
  africa: 'text-green-600',
  outros: 'text-slate-600',
};

export function getCurrenciesByRegion(region: string): Currency[] {
  return Object.values(CURRENCIES).filter((c) => c.region === region);
}

export function getPrincipalCurrencies(): Currency[] {
  return Object.values(CURRENCIES).filter((c) => c.isPrincipal);
}

export function getAllCurrencies(): Currency[] {
  return Object.values(CURRENCIES);
}
